TreatShop/Models/Flavor.cs
using System.Collections.Generic;

namespace TreatShop.Models
{
  public class Flavor 
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<TreatFlavor>();
    }
    public int FlavorId { get; set; }
    public string FlavorName { get; set; }
    public virtual ICollection<TreatFlavor> JoinEntities { get; }
  }
}

TreatShop/Controllers/FlavorController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using TreatShop.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace TreatShop.Controllers
{
  [Authorize]  
  public class FlavorsController:Controller
  {
    private readonly TreatShopContext _db;
    private readonly UserManager <ApplicationUser> _userManager;

    public FlavorsController(TreatShopContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }
    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [AllowAnonymous]

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Create (Flavor flavor, int TreatId)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      if(TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() {TreatId = TreatId, FlavorId = flavor.FlavorId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
    if (TreatId != 0)
    {
      _db.TreatFlavor.Add(new TreatFlavor() {TreatId = TreatId, FlavorId = flavor.FlavorId});
    }
    _db.Entry(flavor).State = EntityState.Modified;
    _db.SaveChanges();
    return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

  [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() {TreatId = TreatId, FlavorId = flavor.FlavorId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor (int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TreatShop/Views/Flavors/AddTreats.cshtml
@model TreatShop.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a treat for this treat: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type = "submit" value="save">
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

TreatShop/Views/Flavors/Create.cshtml
@model TreatShop.Models.Flavor

<h4>Add a flavor</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FlavorName)
  @Html.TextBoxFor(model =>model.FlavorName)
  <input type="submit" value ="Add flavor">
}
<p>@Html.ActionLink("View treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TreatShop/Views/Flavors/Delete.cshtml
@model TreatShop.Models.Flavor

<h2>Are you sure you want to delete this treat?</h2>

@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

@Html.ActionLink("Home", "Index", "Home")

TreatShop/Views/Flavors/Details.cshtml
@model TreatShop.Models.Flavor;

<h2>Flavor Details</h2>

<h3>@Html.DisplayNameFor(model => model.FlavorName): @Html.DisplayFor(model => model.FlavorName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor has no logged treats</p>
}
else
{
  <h4>This flavor is part of these treats: </h4>
  <ul>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Treat.TreatName</li>
      @using(Html.BeginForm("DeleteTreat", "Flavors"))
      {
        @Html.Hidden("joinId", @join.TreatFlavorId)
        <input type ="submit" value = "Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add an additional treat for this flavor", "AddFlavor", new {id = Model.FlavorId})</p>
<p>@Html.ActionLink("Edit this flavor", "Edit", new {id = Model.FlavorId})</p>
<p>@Html.ActionLink("Remove this flavor", "Delete", new {id = Model.FlavorId})</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TreatShop/Views/Flavors/Edit.cshtml
@model TreatShop.Models.Flavor

<h2>Edit Flavor</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.FlavorName)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.FlavorName)
  @Html.EditorFor(model => model.FlavorName)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save">
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

TreatShop/Views/Flavors/Index.cshtml
<h1>Flavors</h1>
@using TreatShop.Models;
@model List<TreatShop.Models.Flavor>
@if (Model.Count == 0)
{
  <h2>This flavor has no logged treats!</h2>
}
else 
{
  @foreach (Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new {id = flavor.FlavorId})</li>
  }
}
<p>@Html.ActionLink("Create a flavor!", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>